[platformio]
default_envs = panel1

[env]
platform = espressif32 @ 6.6.0
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_filters = send_on_enter
lib_deps =
    fastled/FastLED @ 3.6.0
    adafruit/Adafruit GFX Library @ 1.11.9
    marcmerlin/FastLED NeoMatrix @ 1.2.0

[env:panel1]
build_flags = -DFLIGHTWALL_TEST_PANELS=1

[env:panel4]
build_flags = -DFLIGHTWALL_TEST_PANELS=4

[env:panel20]
build_flags = -DFLIGHTWALL_TEST_PANELS=20
